### ISSUE TITLE
Integrate Netlify CMS

### ISSUE THREAD

**Issue by resir014** [resir014/resir014.xyz#17]
It's time to integrate this website with Netlify CMS! Will probably do this during the livestream I promised.

Reference implementation: https://github.com/netlify-templates/gatsby-starter-netlify-cms

## Todo

* [ ] Move all post images to `/static/uploads`
  * **Bonus:** Enable Git LFS?
* [ ] Enable [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images) to let gatsby-remark-images resolve to absolute paths
* [ ] Install Netlify CMS + configure for posts
  * [ ] Article
  * [ ] Bookmark
  * [ ] Jam
  * [ ] Note
  * [ ] Photo
  * [ ] Video

**Comment by resir014** [comment]
Closing this. Still re-evaluating the CMS choices we want.
