### ISSUE TITLE
improve content structure + pipeline

### ISSUE THREAD

**Issue by resir014** [resir014/resir014.xyz#180]
![image](https://user-images.githubusercontent.com/5663877/129444172-ac671505-c5fc-418e-a98b-a954e16175ae.png)

## tasks

- [x] improve page generation
- [x] refactor `[...slug].tsx` page into their own files
- [x] refactor all content folders into single `_content` folder
